// The BRIEF — the ONE artifact Kage ever writes into a product repo.
//
// Team memory lives in the shadow repo; the product repo carries a single generated fenced
// block inside the AGENTS.md/CLAUDE.md the team already has. That file belongs to the team,
// not to Kage — the old model (405 packets, 40% of tracked files, memory noise in 200 of 200
// commits) is exactly what this module retires. So the splice is surgical: everything outside
// the fences is preserved byte-for-byte, and applying the same brief twice yields identical
// bytes — a no-op refresh must never show up as a diff in someone's PR.

import { existsSync } from "node:fs";
import { resolve } from "node:path";
import type { Card } from "./types.js";

export const BRIEF_BEGIN = "<!-- kage:begin -->";
export const BRIEF_END = "<!-- kage:end -->";

/** DIRECTION.md's contract: the whole block, fences included, stays under ~200 lines. */
const DEFAULT_MAX_LINES = 200;

/**
 * The first sentence of a claim, flattened to one line. The terminator must be followed by
 * whitespace (or the end) so a dot inside "src/limits.ts" or "v4.0.1" never ends a sentence
 * mid-path. A claim with no terminator is one sentence — use all of it.
 */
function firstSentence(claim: string): string {
  const flat = claim.trim().replace(/\s+/g, " ");
  const match = /^.*?[.!?](?=\s|$)/.exec(flat);
  return match ? match[0] : flat;
}

/**
 * Compile the block from the store's cards. Deterministic: the same cards in any input order
 * produce the same bytes, because the store commits the target file's repo and spurious
 * diffs would drown the real ones.
 */
export function composeBrief(cards: Card[], opts?: { maxLines?: number }): string {
  const maxLines = opts?.maxLines ?? DEFAULT_MAX_LINES;

  // Approved only, and stale NEVER. The brief is always-on context served to every session —
  // a stale claim here would reach every agent on every task, the exact failure this product
  // exists to prevent. Stale cards are withheld and counted elsewhere, never silently shipped.
  const eligible = cards.filter((card) => card.state === "approved" && card.verify !== "stale");

  // Verified outranks unverified; within each band, newest knowledge first. ISO-8601 UTC
  // timestamps sort lexicographically, so string comparison IS chronological order.
  const ranked = [...eligible].sort((a, b) => {
    if (a.verify !== b.verify) return a.verify === "verified" ? -1 : 1;
    return b.updatedAt.localeCompare(a.updatedAt);
  });

  // The cap counts TOTAL lines — the two fences and the header spend 3 of them. Excess cards
  // fall off the bottom (the lowest-ranked go first), and the header confesses the count:
  // a brief that truncated silently would be a measurement lie.
  const room = Math.max(0, maxLines - 3);
  const kept = ranked.slice(0, room);
  const dropped = ranked.length - kept.length;

  const count = `${kept.length} card${kept.length === 1 ? "" : "s"}`;
  const header =
    dropped > 0
      ? `<!-- ${count}, ${dropped} dropped to fit ${maxLines} lines; generated by Kage — edit cards, not this block -->`
      : `<!-- ${count}; generated by Kage — edit cards, not this block -->`;

  const lines = kept.map((card) => {
    // Unverified is stated on the line itself: the agent reading the brief has no other
    // channel for trust state, and an unmarked unverified claim would read as verified.
    const suffix = card.verify === "unverified" ? " (unverified)" : "";
    return `- [${card.kind}] ${card.title} — ${firstSentence(card.claim)} (${card.id})${suffix}`;
  });

  return [BRIEF_BEGIN, header, ...lines, BRIEF_END].join("\n");
}

/**
 * Splice the brief into the target file's current content. Three cases, one promise: nothing
 * the team wrote is ever altered.
 *
 *   file absent (null)  →  the block is the whole file, plus the POSIX trailing newline
 *   block present       →  replace exactly the span from begin-fence to end-fence
 *   block absent        →  append below the team's prose, separated by one blank line
 *
 * Idempotence is structural, not incidental: the brief carries its own fences, so a second
 * apply finds the exact span the first one wrote and writes the same bytes over it.
 */
export function applyBrief(existing: string | null, brief: string): string {
  // An empty file gets the same treatment as an absent one — prepending blank separator
  // lines to nothing would put garbage above the block.
  if (existing === null || existing === "") return brief + "\n";

  const begin = existing.indexOf(BRIEF_BEGIN);
  const end = begin >= 0 ? existing.indexOf(BRIEF_END, begin) : -1;

  if (begin >= 0 && end >= 0) {
    return existing.slice(0, begin) + brief + existing.slice(end + BRIEF_END.length);
  }

  // No block (or a mangled half-block we refuse to guess at — appending a whole new one is
  // recoverable in review; a wrong splice silently eats the team's prose).
  const separator = existing.endsWith("\n") ? "\n" : "\n\n";
  return existing + separator + brief + "\n";
}

/**
 * Which file carries the block. AGENTS.md is the cross-agent convention and wins when the
 * team has one; CLAUDE.md is the installed-base fallback. When neither exists we name
 * AGENTS.md — creating the vendor-neutral file, not planting a vendor-specific one.
 */
export function briefTarget(projectDir: string): string {
  const agents = resolve(projectDir, "AGENTS.md");
  if (existsSync(agents)) return agents;
  const claude = resolve(projectDir, "CLAUDE.md");
  if (existsSync(claude)) return claude;
  return agents;
}
